version: '3'

services:

  myapp-mysql:
    image: mysql:8.0.19
    environment:
      - MYSQL_ROOT_PASSWORD=2864
    ports:
      - 3306:3306

  myapp-main:
    image: rush-hour
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=2864
      - DATABASE_PORT=3306